### ISSUE TITLE
Main Method in this example.

### ISSUE THREAD

**Issue by tusharuit25** [tinodj/mk-fiscal-printer-driver#1]
Hey Can you give me example to starting point with your program. I know you must be busy but your little help will be much appriciated.

**Comment by tinodj** [comment]
Is this really relevant for you? How you find this useful?

**Comment by tusharuit25** [comment]
Yes I am working for Macedonian Client who need to do this sort of printing at his hotel.

**Comment by tusharuit25** [comment]
I need working example ! so I can convert this to C# and it would eventually part of my actual production project.

**Comment by tusharuit25** [comment]
And thank you for your immediate response to my comment.

**Comment by tinodj** [comment]
Working example is really simple to produce. 

Something like this:
```
public static void main(String[] args){
	Product p = new Product('1','name',1);
	ProductOnAccount poa = new ProductOnAccount(p, 1);
	FiscalAccount a = new FiscalAccount();
	a.addProductOnAccount(poa);
	FiscalPrinter fp = new FiscalPrinter();
	fp.print(a);
}
```

Please note this is a code I have produced 16 years ago and it is not support channel, neither how-to tutorial. I am really glad if that helps you, but I am not not providing support about it here :)
