### ISSUE TITLE
This communication library is no more compatible with Java 8

### ISSUE THREAD

**Issue by tusharuit25** [tinodj/mk-fiscal-printer-driver#2]
what is solution for that?

**Comment by tinodj** [comment]
why it is not? What is the error message you are getting?

**Comment by tusharuit25** [comment]
Comm library had JAVA 6 support now comm library does not work with JAVA 8

**Comment by tusharuit25** [comment]
Secondly sendCommand function is incompletely implemented what are you exactly doing there?

**Comment by tusharuit25** [comment]
` public void sendCommand(int cmd, int[] data) throws Exception{
        byte seq = SequenceGenerator.getNewSeq();
        int i=0;
        while (i<5 && !this.sendCommand(cmd,data)){
            i++;
        }
        if (i==5){
            throw new Exception("Printer not working");
        }
    }`

**Comment by tinodj** [comment]
> Secondly sendCommand function is incompletely implemented what are you exactly doing there?

I agree. This was a bug. Now it is fixed. See this commit/change: https://github.com/tinodj/mk-fiscal-printer-driver/commit/fc0859c6cc0b538bbd636083e6a7b66184ceab17

**Comment by tinodj** [comment]
> Comm library had JAVA 6 support now comm library does not work with JAVA 8

Not sure what you are talking about. Comm library - you need to download for the OS you use. Try searching javax comm implementation windows/linux, whatever you plan to use. For linux, you can find here: 

https://www.oracle.com/java/technologies/java-archive-misc-downloads.html

In addition check this thread: 
https://stackoverflow.com/questions/3959743/javax-comm-api-on-64-bit-windows

**Comment by tusharuit25** [comment]
thanks for suggestion. will get back to you!

**Comment by tusharuit25** [comment]
We wish you to work on this. Could please let me know you contact details so that we can get in in touch with you and discuss more about commercials and things like that.
Awaiting for your kind reply.

**Comment by tinodj** [comment]
Please write me on email that is on my profile.
